services:
  web:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/test2.lan.conf:/etc/nginx/conf.d/test2.lan.conf
      - ./html:/html
    networks:
      rede_test:
        aliases:
          - test2.lan
  
  # apacheserver:
  #   image: httpd:lastet
  #   volumes:
  #     -./vue-material-dashboard/dist:/usr/local/apache2/htdocs
  #   networks:
  #     - rede_interna
  cliente:
    hostname: cliente
    image: brunosct/debian12-cliente-firefox
    networks:
      - rede_test
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  rede_test:
