services:
  web:
    build: apache
    hostname: web
    # command: tail -f /dev/null
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app
      - ./apache/wordpress.conf:/etc/apache2/sites-enabled/wordpress.conf
      - ./apache/certs:/certificados
    networks:
      rede_test:
        aliases:
          - daw.loseyourip.com
          - www.daw.loseyourip.com

  cliente:
    hostname: cliente
    image: brunosct/debian12-cliente-firefox
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - rede_test

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: wordpress
      MARIADB_USER: nico
      MARIADB_PASSWORD: abc123.
    volumes:
      - datos:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - rede_test
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - rede_test

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=db
    networks:
      - rede_test

networks:
  rede_test:

volumes:
  datos:
