# Generated by Django 4.2.18 on 2025-02-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toExercise', '0002_exercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(null=True, unique=True, upload_to='toExercise/images'),
        ),
    ]
